import { Link, createFileRoute } from "@tanstack/react-router";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/data")({
  head: () =>
    pageHead({
      title: "How your data is handled",
      path: "/data",
      description:
        "What RockHound GO stores on your device, what it sends to its AI provider and when, and how to export or erase your data.",
    }),
  component: DataPage,
});

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: "Stored only on this device",
    body: [
      "Your GeoDex (specimens, notes, photos), trips, saved sites, quests, badges and progress are kept in this browser's storage on this device. There are no accounts, so nothing is synced to a server.",
      "Clearing your browser's site data, uninstalling the app, or switching devices removes it. Use Export on the Progress page to keep a backup file.",
    ],
  },
  {
    title: "Sent to our AI provider (xAI) — only when you use these features",
    body: [
      "Photo identification: the photo you choose, resized to 768 px, is sent to xAI to identify the specimen.",
      "Clover: your question, the last 16 messages of the conversation, your field name, companion level, mood, energy, streak, today's find count and up to 16 specimen names from your GeoDex are sent to xAI to generate a reply.",
      "Voice: when you speak to Clover, the recording is sent to xAI to transcribe it, and Clover's reply text is sent to xAI to generate speech.",
      "Nothing is sent to xAI unless you start one of these features. The offline field key, Mineralpedia, map, GeoDex and trips never send your data anywhere.",
    ],
  },
  {
    title: "Camera, microphone and location",
    body: [
      "The camera opens only when you tap to scan, and the microphone only when you talk to Clover. RockHound GO does not request your location.",
    ],
  },
  {
    title: "Abuse protection",
    body: [
      "To stop the AI features being misused, the server counts requests per IP address. Those counts are held in memory for up to 24 hours and are not written to a database.",
    ],
  },
  {
    title: "No ads, no tracking",
    body: ["RockHound GO has no advertising, no analytics scripts and no tracking cookies."],
  },
  {
    title: "AI results can be wrong",
    body: [
      "Identifications and Clover's answers are generated by AI and can be wrong. Confirm with field tests, and never rely on them to decide whether something is safe, valuable or legal to collect. Land-status notes on the map are unverified unless a source and check date are shown.",
    ],
  },
];

function DataPage() {
  return (
    <article className="space-y-6">
      <header>
        <p className="text-xs uppercase tracking-[0.18em] text-frost">Your data</p>
        <h1 className="mt-1 font-display text-2xl text-fg">How your data is handled</h1>
        <p className="mt-2 text-sm leading-relaxed text-muted">
          A plain description of what this app stores and sends today.
        </p>
      </header>
      {SECTIONS.map((s) => (
        <section key={s.title} className="space-y-2">
          <h2 className="font-display text-lg text-fg">{s.title}</h2>
          {s.body.map((p) => (
            <p key={p.slice(0, 32)} className="text-sm leading-relaxed text-muted">
              {p}
            </p>
          ))}
        </section>
      ))}
      <Link
        to="/profile"
        className="inline-flex min-h-12 items-center rounded-md border border-line-strong px-4 text-sm text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-frost"
      >
        Export or erase your data
      </Link>
    </article>
  );
}
