/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloverRouteImport } from './routes/clover'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DataRouteImport } from './routes/data'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PediaRouteImport } from './routes/pedia'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ExploreIdRouteImport } from './routes/explore_.$id'
import { Route as PediaIdRouteImport } from './routes/pedia_.$id'
import { Route as VaultIdRouteImport } from './routes/vault_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloverRoute = CloverRouteImport.update({
  id: '/clover',
  path: '/clover',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PediaRoute = PediaRouteImport.update({
  id: '/pedia',
  path: '/pedia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIdRoute = ExploreIdRouteImport.update({
  id: '/explore_/$id',
  path: '/explore/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PediaIdRoute = PediaIdRouteImport.update({
  id: '/pedia_/$id',
  path: '/pedia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault_/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRoute
  '/explore/$id': typeof ExploreIdRoute
  '/pedia/$id': typeof PediaIdRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRoute
  '/explore/$id': typeof ExploreIdRoute
  '/pedia/$id': typeof PediaIdRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRoute
  '/explore_/$id': typeof ExploreIdRoute
  '/pedia_/$id': typeof PediaIdRoute
  '/vault_/$id': typeof VaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clover'
    | '/community'
    | '/data'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/sitemap.xml'
    | '/trips'
    | '/vault'
    | '/explore/$id'
    | '/pedia/$id'
    | '/vault/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clover'
    | '/community'
    | '/data'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/sitemap.xml'
    | '/trips'
    | '/vault'
    | '/explore/$id'
    | '/pedia/$id'
    | '/vault/$id'
  id:
    | '__root__'
    | '/'
    | '/clover'
    | '/community'
    | '/data'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/sitemap.xml'
    | '/trips'
    | '/vault'
    | '/explore_/$id'
    | '/pedia_/$id'
    | '/vault_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloverRoute: typeof CloverRoute
  CommunityRoute: typeof CommunityRoute
  DataRoute: typeof DataRoute
  ExploreRoute: typeof ExploreRoute
  IdentifyRoute: typeof IdentifyRoute
  MarketRoute: typeof MarketRoute
  PediaRoute: typeof PediaRoute
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripsRoute: typeof TripsRoute
  VaultRoute: typeof VaultRoute
  ExploreIdRoute: typeof ExploreIdRoute
  PediaIdRoute: typeof PediaIdRoute
  VaultIdRoute: typeof VaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clover': {
      id: '/clover'
      path: '/clover'
      fullPath: '/clover'
      preLoaderRoute: typeof CloverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedia': {
      id: '/pedia'
      path: '/pedia'
      fullPath: '/pedia'
      preLoaderRoute: typeof PediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_/$id': {
      id: '/explore_/$id'
      path: '/explore/$id'
      fullPath: '/explore/$id'
      preLoaderRoute: typeof ExploreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedia_/$id': {
      id: '/pedia_/$id'
      path: '/pedia/$id'
      fullPath: '/pedia/$id'
      preLoaderRoute: typeof PediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault_/$id': {
      id: '/vault_/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloverRoute: CloverRoute,
  CommunityRoute: CommunityRoute,
  DataRoute: DataRoute,
  ExploreRoute: ExploreRoute,
  IdentifyRoute: IdentifyRoute,
  MarketRoute: MarketRoute,
  PediaRoute: PediaRoute,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripsRoute: TripsRoute,
  VaultRoute: VaultRoute,
  ExploreIdRoute: ExploreIdRoute,
  PediaIdRoute: PediaIdRoute,
  VaultIdRoute: VaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
