/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloverRouteImport } from './routes/clover'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PediaRouteImport } from './routes/pedia'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ExploreIdRouteImport } from './routes/explore.$id'
import { Route as PediaIdRouteImport } from './routes/pedia.$id'
import { Route as VaultIdRouteImport } from './routes/vault.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloverRoute = CloverRouteImport.update({
  id: '/clover',
  path: '/clover',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PediaRoute = PediaRouteImport.update({
  id: '/pedia',
  path: '/pedia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIdRoute = ExploreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const PediaIdRoute = PediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PediaRoute,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRouteWithChildren
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRouteWithChildren
  '/explore/$id': typeof ExploreIdRoute
  '/pedia/$id': typeof PediaIdRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRouteWithChildren
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRouteWithChildren
  '/explore/$id': typeof ExploreIdRoute
  '/pedia/$id': typeof PediaIdRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clover': typeof CloverRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRouteWithChildren
  '/identify': typeof IdentifyRoute
  '/market': typeof MarketRoute
  '/pedia': typeof PediaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/safety': typeof SafetyRoute
  '/trips': typeof TripsRoute
  '/vault': typeof VaultRouteWithChildren
  '/explore/$id': typeof ExploreIdRoute
  '/pedia/$id': typeof PediaIdRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clover'
    | '/community'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/trips'
    | '/vault'
    | '/explore/$id'
    | '/pedia/$id'
    | '/vault/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clover'
    | '/community'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/trips'
    | '/vault'
    | '/explore/$id'
    | '/pedia/$id'
    | '/vault/$id'
  id:
    | '__root__'
    | '/'
    | '/clover'
    | '/community'
    | '/explore'
    | '/identify'
    | '/market'
    | '/pedia'
    | '/profile'
    | '/quests'
    | '/safety'
    | '/trips'
    | '/vault'
    | '/explore/$id'
    | '/pedia/$id'
    | '/vault/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloverRoute: typeof CloverRoute
  CommunityRoute: typeof CommunityRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  IdentifyRoute: typeof IdentifyRoute
  MarketRoute: typeof MarketRoute
  PediaRoute: typeof PediaRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  SafetyRoute: typeof SafetyRoute
  TripsRoute: typeof TripsRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clover': {
      id: '/clover'
      path: '/clover'
      fullPath: '/clover'
      preLoaderRoute: typeof CloverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedia': {
      id: '/pedia'
      path: '/pedia'
      fullPath: '/pedia'
      preLoaderRoute: typeof PediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$id': {
      id: '/explore/$id'
      path: '/$id'
      fullPath: '/explore/$id'
      preLoaderRoute: typeof ExploreIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/pedia/$id': {
      id: '/pedia/$id'
      path: '/$id'
      fullPath: '/pedia/$id'
      preLoaderRoute: typeof PediaIdRouteImport
      parentRoute: typeof PediaRoute
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreIdRoute: typeof ExploreIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreIdRoute: ExploreIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface PediaRouteChildren {
  PediaIdRoute: typeof PediaIdRoute
}

const PediaRouteChildren: PediaRouteChildren = {
  PediaIdRoute: PediaIdRoute,
}

const PediaRouteWithChildren = PediaRoute._addFileChildren(PediaRouteChildren)

interface VaultRouteChildren {
  VaultIdRoute: typeof VaultIdRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultIdRoute: VaultIdRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloverRoute: CloverRoute,
  CommunityRoute: CommunityRoute,
  ExploreRoute: ExploreRouteWithChildren,
  IdentifyRoute: IdentifyRoute,
  MarketRoute: MarketRoute,
  PediaRoute: PediaRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  SafetyRoute: SafetyRoute,
  TripsRoute: TripsRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
